In [1]:
import seaborn as sns
import pylab as rcParams
import matplotlib.pyplot as plt
from matplotlib import rc
import matplotlib 
import pandas as pd 
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Dropout, GRU
from sklearn.preprocessing import MinMaxScaler
from  sklearn.model_selection import TimeSeriesSplit
from keras.callbacks import EarlyStopping

2023-10-25 21:31:28.788325: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-10-25 21:31:28.806144: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-25 21:31:28.806188: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-25 21:31:28.806199: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-25 21:31:28.810155: I tensorflow/core/platform/cpu_feature_g

In [2]:
df=pd.read_csv('/home/j/usfq/tesis/StockPredictionModels/Data/Complete.csv')
df

Date ticker_symbol  p_sentiment        Open        High  \
0     2015-01-02          AAPL     0.857156   27.847500   27.860001   
1     2015-01-02          AMZN     0.731959   15.629000   15.737500   
2     2015-01-02          GOOG     0.883473   26.378078   26.490770   
3     2015-01-02         GOOGL     0.908735   26.629999   26.790001   
4     2015-01-02          MSFT     0.804051   46.660000   47.419998   
...          ...           ...          ...         ...         ...   
7531  2019-12-30          AMZN     0.748412   93.699997   94.199997   
7532  2019-12-30          GOOG     0.676151   67.500000   67.650002   
7533  2019-12-30         GOOGL     0.705876   67.840500   67.849998   
7534  2019-12-30          MSFT     0.762997  158.990005  159.020004   
7535  2019-12-30          TSLA     0.588330   28.586000   28.600000   

             Low       Close  unrate  psr       m2    dspic      pce    reer  \
0      26.837500   27.332500     5.7  8.0  11759.1  13224.7  12036.5  106.11   
1      15.348000   15.426000     5.7  8.0  11759.1  13224.7  12036.5  106.11   
2      26.133251   26.168653     5.7  8.0  11759.1  13224.7  12036.5  106.11   
3      26.393999   26.477501     5.7  8.0  11759.1  13224.7  12036.5  106.11   
4      46.540001   46.759998     5.7  8.0  11759.1  13224.7  12036.5  106.11   
...          ...         ...     ...  ...      ...      ...      ...     ...   
7531   92.030998   92.344498     3.6  7.3  15416.2  14844.1  14686.3  116.51   
7532   66.700996   66.806999     3.6  7.3  15416.2  14844.1  14686.3  116.51   
7533   66.891998   66.985497     3.6  7.3  15416.2  14844.1  14686.3  116.51   
7534  156.729996  157.589996     3.6  7.3  15416.2  14844.1  14686.3  116.51   
7535   27.284000   27.646667     3.6  7.3  15416.2  14844.1  14686.3  116.51   

            ir      ffer        tcs    indpro     ccpi  
0     1.881500  0.114839  1069010.0  102.8479  239.811  
1     1.881500  0.114839  1069010.0  102.8479  239.811  
2     1.881500  0.114839  1069010.0  102.8479  239.811  
3     1.881500  0.114839  1069010.0  102.8479  239.811  
4     1.881500  0.114839  1069010.0  102.8479  239.811  
...        ...       ...        ...       ...      ...  
7531  1.862857  1.550968  1458485.0  101.6179  265.651  
7532  1.862857  1.550968  1458485.0  101.6179  265.651  
7533  1.862857  1.550968  1458485.0  101.6179  265.651  
7534  1.862857  1.550968  1458485.0  101.6179  265.651  
7535  1.862857  1.550968  1458485.0  101.6179  265.651  

[7536 rows x 18 columns]

In [3]:
#turn date into unix time
#df['Date'] = pd.to_datetime(df['Date'])
#df['Date'] = df['Date'].apply(lambda x: x.timestamp())
#df

In [4]:
#generate new dataframes for each ticker_symbol
df_dict={}
for key in df['ticker_symbol'].unique():
    df_dict[key]=df[df['ticker_symbol']==key]
    df_dict[key]=df_dict[key].drop(columns=['ticker_symbol'])
    df_dict[key]=df_dict[key].sort_values(by=['Date']).reset_index(drop=True)
    #df_dict[key]=df_dict[key].drop(columns=['Date'])
    print(key,df_dict[key].shape)
    print(df_dict[key].head(-1))

AAPL (1252, 17)
            Date  p_sentiment       Open       High        Low      Close  \
0     2015-01-02     0.857156  27.847500  27.860001  26.837500  27.332500   
1     2015-01-05     0.744531  27.072500  27.162500  26.352501  26.562500   
2     2015-01-06     0.769826  26.635000  26.857500  26.157499  26.565001   
3     2015-01-07     0.773995  26.799999  27.049999  26.674999  26.937500   
4     2015-01-08     0.770458  27.307501  28.037500  27.174999  27.972500   
...          ...          ...        ...        ...        ...        ...   
1246  2019-12-20     0.775477  70.557503  70.662498  69.639999  69.860001   
1247  2019-12-23     0.759453  70.132500  71.062500  70.092499  71.000000   
1248  2019-12-24     0.742264  71.172501  71.222504  70.730003  71.067497   
1249  2019-12-26     0.670220  71.205002  72.495003  71.175003  72.477501   
1250  2019-12-27     0.760582  72.779999  73.492500  72.029999  72.449997   

      unrate  psr       m2    dspic      pce    reer       

In [5]:
ticker='AAPL'

In [6]:
df=df_dict[ticker].copy()
df.head()

Date  p_sentiment       Open       High        Low      Close  \
0  2015-01-02     0.857156  27.847500  27.860001  26.837500  27.332500   
1  2015-01-05     0.744531  27.072500  27.162500  26.352501  26.562500   
2  2015-01-06     0.769826  26.635000  26.857500  26.157499  26.565001   
3  2015-01-07     0.773995  26.799999  27.049999  26.674999  26.937500   
4  2015-01-08     0.770458  27.307501  28.037500  27.174999  27.972500   

   unrate  psr       m2    dspic      pce    reer      ir      ffer  \
0     5.7  8.0  11759.1  13224.7  12036.5  106.11  1.8815  0.114839   
1     5.7  8.0  11759.1  13224.7  12036.5  106.11  1.8815  0.114839   
2     5.7  8.0  11759.1  13224.7  12036.5  106.11  1.8815  0.114839   
3     5.7  8.0  11759.1  13224.7  12036.5  106.11  1.8815  0.114839   
4     5.7  8.0  11759.1  13224.7  12036.5  106.11  1.8815  0.114839   

         tcs    indpro     ccpi  
0  1069010.0  102.8479  239.811  
1  1069010.0  102.8479  239.811  
2  1069010.0  102.8479  239.811  
3  1069010.0  102.8479  239.811  
4  1069010.0  102.8479  239.811

In [7]:
#putting the close column on the last position
df=df[['Date',
'p_sentiment',
 'Open',
 'High',
 'Low',
 'unrate',
 'psr',
 'm2',
 'dspic',
 'pce',
 'reer',
 'ir',
 'ffer',
 'tcs',
 'indpro',
 'ccpi',
  'Close',]]

In [8]:
dates = pd.to_datetime(df['Date'])

In [9]:
cols=list(df)[1:]
cols

['p_sentiment',
 'Open',
 'High',
 'Low',
 'unrate',
 'psr',
 'm2',
 'dspic',
 'pce',
 'reer',
 'ir',
 'ffer',
 'tcs',
 'indpro',
 'ccpi',
 'Close']

In [10]:
df_for_training = df[cols].astype(float)

In [11]:
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(df_for_training)

In [12]:
print(scaled_data)

[[0.95039792 0.10635442 0.09772617 ... 0.77924797 0.         0.0943931 ]
 [0.67576714 0.09094073 0.08393475 ... 0.77924797 0.         0.07908343]
 [0.73744721 0.08223946 0.0779041  ... 0.77924797 0.         0.07913316]
 ...
 [0.49456218 0.96867548 0.98027688 ... 0.57323507 1.         0.9919973 ]
 [0.71490676 1.         1.         ... 0.57323507 1.         0.99145044]
 [0.68512664 0.9917462  0.99367278 ... 0.57323507 1.         1.        ]]


In [13]:
#split scaled data into training, val and testing
#train_data=scaled_data[0:1000,:]
#val_data=scaled_data[1000:1125,:]
#test_data=scaled_data[1125:,:]

In [14]:
n_future = 1 # Number of days we want to predict into the future
n_past = 7 # Number of past days we want to use to predict the future

In [15]:
X=[]
y=[]
for i in range(n_past, len(scaled_data) - n_future +1):
    X.append(scaled_data[i - n_past:i, 0:df_for_training.shape[1]])
    y.append(scaled_data[i + n_future - 1:i + n_future, len(cols)-1])

In [16]:
#shape of X_s and y_s
X, y = np.array(X), np.array(y)
print(X.shape)
print(y.shape)

(1245, 7, 16)
(1245, 1)


In [17]:
X_train=X[0:1200,:]
X_test=X[1200:,:]
y_train=y[0:1200,:]
y_test=y[1200:,:]

#early stopping


In [18]:
tscv = TimeSeriesSplit(n_splits=10)
y_test=np.repeat(y_test,16,axis=1)
y_test=scaler.inverse_transform(y_test)[:,-1] 
for train_index, val_index in tscv.split(X_train):
    early_stop=EarlyStopping(monitor='val_loss',patience=10)
    X_train, X_val = X[train_index], X[val_index]
    y_train, y_val = y[train_index], y[val_index]
    model=Sequential()
    model.add(GRU(2048, activation='relu', input_shape=(X_train.shape[1], X_train.shape[2]), return_sequences=False))
    model.add(Dense(y_train.shape[1]))
    model.compile(optimizer='adam',loss='mse')
  
    history=model.fit(X_train,y_train,epochs=100,validation_data=(X_val,y_val),shuffle=False, callbacks=[early_stop])
    plt.plot(history.history['loss'],label='train')
    plt.plot(history.history['val_loss'],label='val')
    plt.legend()
    plt.show()
    y_pred=model.predict(X_test)
    y_pred.shape

    pred=np.repeat(y_pred,16,axis=1)

    pred=scaler.inverse_transform(pred)[:,-1]
    

    print(pred.shape)
    print(y_test.shape)

    #plotting the results
    plt.plot(y_test, label='real')
    plt.plot(pred, label='pred') 
    plt.legend()
    plt.show()


2023-10-25 21:31:29.949785: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-10-25 21:31:30.043504: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-10-25 21:31:30.043541: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-10-25 21:31:30.045808: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:880] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-10-25 21:31:30.045843: I tensorflow/compile

NameError: name 'TransformerEncoder' is not defined